# http://materialdesignicons.com/cdn/7.4.47/

# Define icons used
font:
  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: icon_font
    size: 48
    bpp: 4
    glyphs: [
      "\U000F0335",  # mdi-lightbulb
      "\U000F042B",  # mdi-printer-3d
      "\U000F0D43",  # mdi-air-filter
      "\U000F1051",  # mdi-led-strip-variant
      "\U000F03D7",  # mdi-package-variant-closed
      "\U000F07D6",  # mdi-led-strip
      "\U000F00AC",  # mdi-blinds-closed
      "\U000F1011",  # mdi-blinds-open
      "\U000F1A4C",  # mdi-lightbulb-night
      "\U000F1087",  # mdi-router-network
      "\U000F036B",  # mdi-message-video
      "\U000F0614",  # mdi-application-outline
      "\U000F07C9",  # mdi-forklift
      "\U000F02AB",  # mdi-gmail
      "\U000F04B1",  # mdi-slack
      "\U000F0633",  # mdi-command
      "\U000F075D",  # mdi-volumeplus
      "\U000F075E",  # mdi-volumeminus
      "\U000F1B2A",  # mdi-faucet-variant
      "\U000F1356",  # mdi-television-ambient-light
      "\U000F156D",  # mdi-sofa-outline
      "\U000F05BC",  # mdi-table-furniture
      "\U000F0821",  # mdi-floor-plan
      "\U000F1425",  # mdi-power-plug-outline
      "\U000F040B",  # mdi-play-box-outline
      "\U000F062C",  # mdi-source-branch
      "\U000F040E",  # mdi-play-pause      
      "\U000F024A",  # mdi-flower
      "\U000F075F",  #mid-volume-mute
      "\U000F0206",  #mdi-exit-to-app
      "\U000F0F1B",  #mdi:play-outline
      "\U000F03E4",  #mdi:pause
      "\U000F04DB",  #mdi:stop
      "\U000F0F28",  #mdi:skip-previous-outline
      "\U000F0F27",  #mdi:skip-next-outline
      "\U000F08BB"  #mdi-cog-outline
      ]

# Map icons to names
substitutions:
  lightbulb:      "\U000F0335"
  printer:        "\U000F042B"
  aircon:         "\U000F0D43"
  ledstrip:       "\U000F1051"
  package:        "\U000F03D7"
  lights:         "\U000F07D6"
  blinds_closed:  "\U000F00AC"
  blinds_open:    "\U000F1011"
  nightlight:     "\U000F1A4C"
  network:        "\U000F1087"
  videocall:      "\U000F036B"
  application:    "\U000F0614"
  forklift:       "\U000F07C9"
  gmail:          "\U000F02AB"
  slack:          "\U000F04B1"
  command:        "\U000F0633"
  volumeplus:     "\U000F075D"
  volumeminus:    "\U000F075E"
  faucet_variant: "\U000F1B2A"
  ambient_light:  "\U000F1356"
  sofa_outline:   "\U000F156D"
  table_furniture: "\U000F05BC"
  floor_plan:     "\U000F0821"
  power_plug:     "\U000F1425"
  play_box:       "\U000F040B"
  source_branch:  "\U000F062C"
  play_pause:     "\U000F040E"
  flower:         "\U000F024A"
  volume_mute:    "\U000F075F"
  cog_outline:    "\U000F08BB"
  exit_to_app:    "\U000F0206"
  play:           "\U000F0F1B"
  pause:          "\U000F03E4"
  stop:           "\U000F04DB"
  skip_previous:  "\U000F0F28"
  skip_next:      "\U000F0F27"
