sensor:
    ## WEATHER SENSORS ##
  - platform: homeassistant
    id: current_temp_sensor
    entity_id: sensor.nanaimo_temperature
    on_value:
     - lvgl.label.update:
         id: weather_page_current_temp
         text: 
           format: "%.1f°C"
           args: [ 'x' ]

  - platform: homeassistant
    id: low_temp_sensor
    entity_id: sensor.nanaimo_low_temperature

  - platform: homeassistant
    id: high_temp_sensor
    entity_id: sensor.nanaimo_high_temperature   

  - platform: homeassistant
    id: icon_code_sensor
    entity_id: sensor.nanaimo_icon_code
    on_value:
     - lvgl.label.update:
         id: weather_page_weather_icon
         text: !lambda |-
          char glyph_code[20];
          switch(int(x)){
            case 1:
              glyph_code = "$wx_9";
              break;
            default: 
              glyph_code = "$wx_0";
            }
          return glyph_code; 

    ## VOLUME LEVEL SENSORS ##
  - platform: homeassistant
    id: living_room_volume
    entity_id: media_player.living_room
    attribute: volume_level
    on_value:
      - lvgl.slider.update:
          id: living_room_volume_slider
          value: !lambda return (x * 100);  

  - platform: homeassistant
    id: dining_room_volume
    entity_id: media_player.zone_12_2
    attribute: volume_level
    on_value:
      - lvgl.slider.update:
          id: dining_room_volume_slider
          value: !lambda return (x * 100);

  - platform: homeassistant
    id: kitchen_volume
    entity_id: media_player.zone_11_2
    attribute: volume_level
    on_value:
      - lvgl.slider.update:
          id: kitchen_volume_slider
          value: !lambda return (x * 100);          

  - platform: homeassistant
    id: deck_volume
    entity_id: media_player.zone_13_2
    attribute: volume_level
    on_value:
      - lvgl.slider.update:
          id: deck_volume_slider
          value: !lambda return (x * 100);  

text_sensor:
    ## WEATHER SENSORS ##
  - platform: homeassistant
    id: summary_sensor  
    entity_id: sensor.nanaimo_summary
    on_value:
     - lvgl.label.update:
        id: weather_page_current_conditions
        text: !lambda return x;
 
  - platform: homeassistant
    id: wind_direction_sensor  
    entity_id: sensor.nanaimo_wind_direction
    on_value:
    - lvgl.label.update:
        id: weather_page_wind_info
        text: !lambda return "Wind\nSpeed:" + id(wind_speed_sensor).state + " km/h\nDirection:" + x;  

  - platform: homeassistant
    id: wind_speed_sensor  
    entity_id: sensor.nanaimo_wind_speed
    on_value:
     - lvgl.label.update:
        id: weather_page_wind_info
        text: !lambda return "Wind\nSpeed:" + x + " km/h\nDirection:" + id(wind_direction_sensor).state;  

  - platform: homeassistant
    id: sun_rise_sensor  
    entity_id: sensor.sun_next_rising
    on_value:
     - lvgl.label.update:
        id: weather_page_sun
        text: !lambda |-
          char sun_rise[9];
          char sun_set[9];
          char reply[50] = "Sun\nRise: ";
          strncpy(sun_rise, x.c_str() + 12, 7);
          strncpy(sun_set, id(sun_set_sensor).state.c_str() + 12, 7);
          sun_rise[0] += 3;
          sun_rise[8]='\0';
          sun_set[0] += 5;
          sun_set[8]='\0';
          strcat(reply, sun_rise);
          strcat(reply, " AM\nSet:   ");
          strcat(reply, sun_set);
          strcat(reply, " PM");
          return reply;
        
  - platform: homeassistant
    id: sun_set_sensor  
    entity_id: sensor.sun_next_setting
    # on_value:
    #  - lvgl.label.update:
    #     id: weather_page_sun
    #     text: !lambda return "Sun\nRise:" + id(sun_rise_sensor).state + "\nSet:" + x;  


  ## NOT FUNCTIONING (but also no errors)
  - platform: homeassistant
    id: nanaimo_forecast_sensor
    entity_id: weather.nanaimo_forecast
    attribute: forecast
    on_value:
     - lvgl.label.update:
         id: weather_page_hourly_forecast
         text: "Weather forecast received!" # !lambda return x;

    ## SPOTIFY TEXT SENSORES ##
  - platform: homeassistant
    id: spotify_title
    entity_id: media_player.spotify_larissajay
    attribute: media_title
    on_value:
      - lvgl.label.update:
          id: info_button_top
          text: !lambda return x;

  - platform: homeassistant
    id: spotify_album
    entity_id: media_player.spotify_larissajay
    attribute: media_album_name
    on_value:
      - lvgl.label.update:
          id: info_button_middle
          text: !lambda return x; 

  - platform: homeassistant
    id: spotify_artist
    entity_id: media_player.spotify_larissajay
    attribute: media_artist
    on_value:
      - lvgl.label.update:
          id: info_button_bottom
          text: !lambda return x; 
      
binary_sensor:
    ## STATE (ON/OFF) SENSORS ##
  - platform: homeassistant
    id: living_room_media_player
    entity_id: media_player.living_room
    publish_initial_state: true
    on_state:
      - if:
          condition:
            lambda: return id(living_room_media_player).state;
          then:
            - lvgl.button.update:
                id: living_room_power_button
                state:
                  checked: true
          else:
            - lvgl.button.update:
                id: living_room_power_button
                state:
                  checked: false

  - platform: homeassistant
    id: dining_room_media_player
    entity_id: media_player.zone_12_2
    publish_initial_state: true
    on_state:
      - if:
          condition:
            lambda: return id(dining_room_media_player).state;
          then:
            - lvgl.button.update:
                id: dining_room_power_button
                state:
                  checked: true
          else:
            - lvgl.button.update:
                id: dining_room_power_button
                state:
                  checked: false

  - platform: homeassistant
    id: kitchen_media_player
    entity_id: media_player.zone_11_2
    publish_initial_state: true
    on_state:
      - if:
          condition:
            lambda: return id(kitchen_media_player).state;
          then:
            - lvgl.button.update:
                id: kitchen_power_button
                state:
                  checked: true
          else:
            - lvgl.button.update:
                id: kitchen_power_button
                state:
                  checked: false

  - platform: homeassistant
    id: deck_media_player
    entity_id: media_player.zone_13_2
    publish_initial_state: true
    on_state:
      - if:
          condition:
            lambda: return id(deck_media_player).state;
          then:
            - lvgl.button.update:
                id: deck_power_button
                state:
                  checked: true
          else:
            - lvgl.button.update:
                id: deck_power_button
                state:
                  checked: false

  - platform: homeassistant
    id: system_power
    entity_id: switch.y_window_socket_1
    publish_initial_state: true
    on_state:
      - if:
          condition:
            lambda: return id(system_power).state;
          then:
            - lvgl.button.update:
                id: system_power_button
                state:
                  checked: true
          else:
            - lvgl.button.update:
                id: system_power_button
                state:
                  checked: false    



