substitutions:
  icon_font: icon_font
  weather_icon_font: weather_icon_font
  text_font: roboto17_font
  large_text_font: roboto19_font
  small_text_font: roboto15_font
  extra_large_text_font: roboto25_font
  super_large_text_font: roboto31_font
  button_on_color: "0xFF8C00"
  button_text_color: "0xFFFFFF"
  button_light_color: "0x363636"
  button_dark_color: "0x262626"
  button_height_single: 102px
  button_width: 150px
  padding: 8px
  radius: 12px
  slider_background_color: "0x505050"
  slider_active_color: "0x2D2D2D"
  slider_knob_color: "0xE5E5E5"

lvgl:
  style_definitions:
    - id: light
      bg_color: $button_light_color

    - id: dark
      bg_color: $button_dark_color
      
    - id: invisible
      bg_opa: TRANSP

  theme:
    button:
      text_font: $text_font
      scroll_on_focus: false
      radius: $radius
      width: $button_width
      height: $button_height_single
      pad_all: $padding
      shadow_width: 0
      text_color: $button_text_color
      checked:
        bg_color: $button_on_color
        text_color: $button_text_color
    slider:
      width: 20px
      height: 200px
      bg_color: 0x333333
      indicator:
        bg_color: 0x555555
      knob:
        bg_color: 0xbbbbbb

