# Online Status
binary_sensor:
  - platform: status
    name: "Online"
    id: ink_ha_connected
    icon: mdi:check-network


sensor:
# Uptime
  - platform: uptime
    name: "Uptime Sensor"
    id: uptime_sensor
    entity_category: diagnostic
    internal: true

# Wifi Signal Strength
  - platform: wifi_signal
    name: "Wifi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
    internal: true
    on_update:
      - lvgl.label.update:
          id: display_wifi_strength
          text: !lambda return "Wifi %d dBm", id(wifi_signal_db).state

# Wifi Signal Strength
  - platform: copy
    source_id: wifi_signal_db
    name: "Wifi Strength"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    icon: mdi:wifi
    entity_category: "diagnostic"
    device_class: ""

# # Wifi Signal Display
# script:
#   - id: wifi_strength_update
#     then:
#       - lvgl.label.update:
#           id: display_wifi_strength
#           text: !lambda |-
#             static char time_buf[17];
#             auto now = id(sntp_time).now();
#             snprintf(time_buf, sizeof(time_buf), "%02d:%02d", now.hour, now.minute);
#             return time_buf;



text_sensor:
# Ip Address
  - platform: wifi_info
    ip_address:
      name: IP Address
      icon: mdi:ip-network

# Esphome Version
  - platform: version
    name: Version
    icon: mdi:package-variant-closed
    hide_timestamp: true
